apiVersion: v1
kind: Pod
metadata:
  name: teastore-db
  labels:
    run: teastore-db
spec:
  containers:
  - name: teastore-db
    image: descartesresearch/teastore-db
    ports:
    - containerPort: 3306
    env:
    - name: USE_POD_IP
      value: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: teastore-registry
  labels:
    run: teastore-registry
spec:
  containers:
  - name: teastore-registry
    image: descartesresearch/teastore-registry
    ports:
    - containerPort: 8080
    env:
    - name: SERVICE_PORT
      value: "8080"
    - name: USE_POD_IP
      value: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: teastore-persistence
  labels:
    run: teastore-persistence
spec:
  containers:
  - name: teastore-persistence
    image: descartesresearch/teastore-persistence
    ports:
    - containerPort: 8080
    env:
    - name: REGISTRY_HOST
      value: "teastore-registry"
    - name: REGISTRY_PORT
      value: "8080"
    - name: SERVICE_PORT
      value: "8080"
    - name: USE_POD_IP
      value: "true"
    - name: DB_HOST
      value: "teastore-db"
    - name: HOST_NAME
      value: "teastore-persistence"
---
apiVersion: v1
kind: Pod
metadata:
  name: teastore-auth
  labels:
    run: teastore-auth
spec:
  containers:
  - name: teastore-auth
    image: descartesresearch/teastore-auth
    ports:
    - containerPort: 8080
    env:
    - name: REGISTRY_HOST
      value: "teastore-registry"
    - name: REGISTRY_PORT
      value: "8080"
    - name: SERVICE_PORT
      value: "8080"
    - name: HOST_NAME
      value: "teastore-auth"
---
apiVersion: v1
kind: Pod
metadata:
  name: teastore-image
  labels:
    run: teastore-image
spec:
  containers:
  - name: teastore-image
    image: descartesresearch/teastore-image
    ports:
    - containerPort: 8080
    env:
    - name: REGISTRY_HOST
      value: "teastore-registry"
    - name: REGISTRY_PORT
      value: "8080"
    - name: SERVICE_PORT
      value: "8080"
    - name: USE_POD_IP
      value: "true"
    - name: HOST_NAME
      value: "teastore-image"
---
apiVersion: v1
kind: Pod
metadata:
  name: teastore-recommender
  labels:
    run: teastore-recommender
spec:
  containers:
  - name: teastore-recommender
    image: descartesresearch/teastore-recommender
    ports:
    - containerPort: 8080
    env:
    - name: REGISTRY_HOST
      value: "teastore-registry"
    - name: REGISTRY_PORT
      value: "8080"
    - name: SERVICE_PORT
      value: "8080"
    - name: USE_POD_IP
      value: "true"
    - name: HOST_NAME
      value: "teastore-recommender"
---
apiVersion: v1
kind: Pod
metadata:
  name: teastore-webui
  labels:
    run: teastore-webui
spec:
  containers:
  - name: teastore-webui
    image: descartesresearch/teastore-webui
    ports:
    - containerPort: 8080
    env:
    - name: REGISTRY_HOST
      value: "teastore-registry"
    - name: REGISTRY_PORT
      value: "8080"
    - name: SERVICE_PORT
      value: "8080"
    - name: USE_POD_IP
      value: "true"
    - name: HOST_NAME
      value: "teastore-webui"