apiVersion: v1
kind: Service
metadata:
  name: teastore-persistence
  labels:
    run: teastore-persistence
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-persistence
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-registry
  labels:
    run: teastore-registry
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-registry
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-auth
  labels:
    run: teastore-auth
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-auth
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-recommender
  labels:
    run: teastore-recommender
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-recommender
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-image
  labels:
    run: teastore-image
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-image
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-webui
  labels:
    run: teastore-webui
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-webui
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-db
  labels:
    run: teastore-db
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    run: teastore-db
